colorscheme palenight

set-option global scrolloff 5,1
add-highlighter global/ number-lines -relative
add-highlighter global/ wrap -word -indent

# key mappings
map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

# enable kakoune-lsp
eval %sh{kak-lsp --kakoune -s $kak_session} 
hook global WinSetOption filetype=(rust|go|javascript|typescript|c) %{
    lsp-enable-window
}

lsp-inlay-diagnostics-enable global
lsp-inlay-hints-enable global

